cmake_minimum_required(VERSION 3.10)

set(ENG_DIR "C:/dev/Visual Studio Code/Rune-Forge/bin/Debug/EDITOR/")
set(PROJ_NAME "Sandbox")
file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "src/*.c")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/../bin/)
add_library(${PROJ_NAME} SHARED ${SOURCES})
target_compile_definitions(${PROJ_NAME} PRIVATE GAME_BUILD_DLL)
target_link_libraries(${PROJ_NAME} "${ENG_DIR}libruneforge.dll")
target_link_libraries(${PROJ_NAME} "${ENG_DIR}librunewall.dll")
target_link_libraries(${PROJ_NAME} "${ENG_DIR}libgaven.dll")
target_include_directories(${PROJ_NAME} PRIVATE "${ENG_DIR}include")
